const std = @import("std");
const transcribe = @import("transcribe.zig");

/// Everything the frontmatter needs that varies per run; the description is
/// derived here from `resource` and `model` so callers can't desync them.
pub const RenderParams = struct {
    /// Recording stem shown as the document title, e.g. "20260825-143000".
    title: []const u8,
    /// Path of the sibling audio file as linked from the note,
    /// e.g. "recordings/20260825-143000.wav".
    resource: []const u8,
    /// ISO-8601 UTC instant the transcript ran (utcTimestamp).
    timestamp: []const u8,
    /// Speech model credited in the description, e.g. "nova-3".
    model: []const u8,
    /// Deepgram language code, e.g. "pt-BR".
    language: []const u8,
    /// Recording length when the WAV header was readable; the frontmatter
    /// field is omitted entirely when null.
    duration_sec: ?f64,
};

/// Renders the full OKF markdown bundle: YAML frontmatter over plain prose,
/// one paragraph per speaker turn. Caller frees the returned bytes.
pub fn render(gpa: std.mem.Allocator, params: RenderParams, utterances: []const transcribe.Utterance) std.mem.Allocator.Error![]u8 {
    var out: std.ArrayList(u8) = .empty;
    errdefer out.deinit(gpa);

    try out.appendSlice(gpa, "---\ntype: ");
    try appendYamlValue(gpa, &out, "Recording Transcript");
    try out.appendSlice(gpa, "\ntitle: ");
    try appendYamlValue(gpa, &out, params.title);

    const description = std.fmt.allocPrint(gpa, "Transcript of {s} generated by Deepgram {s}.", .{ params.resource, params.model }) catch return error.OutOfMemory;
    defer gpa.free(description);
    try out.appendSlice(gpa, "\ndescription: ");
    try appendYamlValue(gpa, &out, description);

    try out.appendSlice(gpa, "\nresource: ");
    try appendYamlValue(gpa, &out, params.resource);
    try out.appendSlice(gpa, "\ntags: [recording, transcript]\ntimestamp: ");
    try appendYamlValue(gpa, &out, params.timestamp);
    try out.appendSlice(gpa, "\nmodel: ");
    try appendYamlValue(gpa, &out, params.model);
    try out.appendSlice(gpa, "\nlanguage: ");
    try appendYamlValue(gpa, &out, params.language);
    if (params.duration_sec) |d| try out.print(gpa, "\nduration_sec: {d}", .{d});

    try out.appendSlice(gpa, "\n---\n");

    // Diarization survives only as paragraph structure — per-utterance
    // timestamps and speaker labels stay out of the file on purpose:
    // consecutive utterances of one speaker join into a single paragraph,
    // a speaker change starts a new one. Text is verbatim; exactly one
    // trailing newline keeps diffs stable.
    var prev_speaker: ?u32 = null;
    for (utterances) |u| {
        if (prev_speaker) |s| {
            if (u.speaker == s) try out.append(gpa, ' ') else try out.appendSlice(gpa, "\n\n");
        } else {
            try out.append(gpa, '\n');
        }
        try out.appendSlice(gpa, u.text);
        prev_speaker = u.speaker;
    }
    try out.append(gpa, '\n');

    return out.toOwnedSlice(gpa);
}

// libc time functions (libc is already linked for miniaudio): UTC naming
// without dragging in tz parsing, mirroring main.zig's local-time idiom.
const Tm = extern struct {
    sec: c_int,
    min: c_int,
    hour: c_int,
    mday: c_int,
    mon: c_int,
    year: c_int,
    wday: c_int,
    yday: c_int,
    isdst: c_int,
    gmtoff: c_long,
    zone: ?[*:0]const u8,
};

extern "c" fn time(now: ?*i64) i64;
extern "c" fn gmtime_r(now: *const i64, result: *Tm) ?*Tm;
// Windows CRT: no _r functions — gmtime fills a static buffer (fine; the
// caller copies it out immediately).
extern "c" fn gmtime(now: *const i64) ?*Tm;

fn utcTime(now: *const i64, out: *Tm) bool {
    if (@import("builtin").os.tag == .windows) {
        const t = gmtime(now) orelse return false;
        out.* = t.*;
        return true;
    }
    return gmtime_r(now, out) != null;
}

/// "YYYY-MM-DDTHH:MM:SSZ" (20 bytes) from the wall clock, in UTC.
pub fn utcTimestamp(out: *[20]u8) void {
    const now: i64 = time(null);
    var tm: Tm = undefined;
    if (!utcTime(&now, &tm)) {
        @memcpy(out, "1970-01-01T00:00:00Z");
        return;
    }
    put4(out[0..4], @intCast(@max(tm.year + 1900, 0)));
    out[4] = '-';
    put2(out[5..7], @intCast(tm.mon + 1));
    out[7] = '-';
    put2(out[8..10], @intCast(tm.mday));
    out[10] = 'T';
    put2(out[11..13], @intCast(tm.hour));
    out[13] = ':';
    put2(out[14..16], @intCast(tm.min));
    out[16] = ':';
    put2(out[17..19], @intCast(tm.sec));
    out[19] = 'Z';
}

fn put2(buf: *[2]u8, v: u32) void {
    buf[0] = '0' + @as(u8, @intCast((v % 100) / 10));
    buf[1] = '0' + @as(u8, @intCast(v % 10));
}

fn put4(buf: *[4]u8, v: u32) void {
    put2(buf[0..2], v / 100);
    put2(buf[2..4], v % 100);
}

/// YAML plain scalars break on ": ", leading indicator characters, and
/// non-printables; anything else is emitted unquoted.
fn yamlNeedsQuotes(s: []const u8) bool {
    if (s.len == 0) return true;
    switch (s[0]) {
        ' ', '!', '&', '*', '-', '?', '|', '>', '%', '@', '`', '"', '\'', '#', '{', '[', '}', ']', ',', ':' => return true,
        else => {},
    }
    for (s, 0..) |ch, i| {
        if (ch < 0x20 or ch == 0x7f) return true;
        if (ch == ':' and i + 1 < s.len and s[i + 1] == ' ') return true;
    }
    return false;
}

/// Appends `s` as a YAML scalar, double-quoted (with minimal escapes) only
/// when plain style would be misread.
fn appendYamlValue(gpa: std.mem.Allocator, out: *std.ArrayList(u8), s: []const u8) std.mem.Allocator.Error!void {
    if (!yamlNeedsQuotes(s)) return out.appendSlice(gpa, s);
    try out.append(gpa, '"');
    for (s) |ch| switch (ch) {
        '"' => try out.appendSlice(gpa, "\\\""),
        '\\' => try out.appendSlice(gpa, "\\\\"),
        '\n' => try out.appendSlice(gpa, "\\n"),
        '\r' => try out.appendSlice(gpa, "\\r"),
        '\t' => try out.appendSlice(gpa, "\\t"),
        else => try out.append(gpa, ch),
    };
    try out.append(gpa, '"');
}

test "utc timestamp renders ISO-8601 UTC" {
    var ts: [20]u8 = undefined;
    utcTimestamp(&ts);
    try std.testing.expectEqualStrings("-", ts[4..5]);
    try std.testing.expectEqualStrings("-", ts[7..8]);
    try std.testing.expectEqualStrings("T", ts[10..11]);
    try std.testing.expectEqualStrings(":", ts[13..14]);
    try std.testing.expectEqualStrings(":", ts[16..17]);
    try std.testing.expectEqual(@as(u8, 'Z'), ts[19]);
    for (ts[0..4]) |c| try std.testing.expect(c >= '0' and c <= '9');
    for ([_]usize{ 5, 6, 8, 9, 11, 12, 14, 15, 17, 18 }) |i| {
        try std.testing.expect(ts[i] >= '0' and ts[i] <= '9');
    }
}

test "renders the spec's golden document byte-for-byte" {
    const utterances = [_]transcribe.Utterance{
        .{ .start_sec = 0.0, .end_sec = 2.1, .speaker = 0, .text = @constCast("Bom dia.") },
        .{ .start_sec = 2.48, .end_sec = 5.03, .speaker = 1, .text = @constCast("Tudo bem?") },
    };
    const doc = try render(std.testing.allocator, .{
        .title = "20260825-143000",
        .resource = "recordings/20260825-143000.wav",
        .timestamp = "2026-08-25T17:30:00Z",
        .model = "nova-3",
        .language = "pt-BR",
        .duration_sec = 12.5,
    }, &utterances);
    defer std.testing.allocator.free(doc);

    try std.testing.expectEqualStrings(
        \\---
        \\type: Recording Transcript
        \\title: 20260825-143000
        \\description: Transcript of recordings/20260825-143000.wav generated by Deepgram nova-3.
        \\resource: recordings/20260825-143000.wav
        \\tags: [recording, transcript]
        \\timestamp: 2026-08-25T17:30:00Z
        \\model: nova-3
        \\language: pt-BR
        \\duration_sec: 12.5
        \\---
        \\
        \\Bom dia.
        \\
        \\Tudo bem?
        \\
    , doc);
}

test "same-speaker utterances merge into one paragraph; a change starts another" {
    const utterances = [_]transcribe.Utterance{
        .{ .start_sec = 0.0, .end_sec = 1.0, .speaker = 0, .text = @constCast("Bom dia.") },
        .{ .start_sec = 1.2, .end_sec = 2.0, .speaker = 0, .text = @constCast("Como vai?") },
        .{ .start_sec = 2.1, .end_sec = 3.0, .speaker = 1, .text = @constCast("Tudo bem.") },
        .{ .start_sec = 3.4, .end_sec = 4.0, .speaker = 1, .text = @constCast("E você?") },
        .{ .start_sec = 4.2, .end_sec = 5.0, .speaker = 0, .text = @constCast("Ótimo.") },
    };
    const doc = try render(std.testing.allocator, .{
        .title = "t",
        .resource = "recordings/r.wav",
        .timestamp = "2026-08-26T12:00:00Z",
        .model = "nova-3",
        .language = "pt-BR",
        .duration_sec = null,
    }, &utterances);
    defer std.testing.allocator.free(doc);

    try std.testing.expectEqualStrings("\n---\n\nBom dia. Como vai?\n\nTudo bem. E você?\n\nÓtimo.\n", doc[std.mem.indexOf(u8, doc, "\n---\n").?..]);
}

test "omits null duration and keeps transcript text verbatim" {
    const utterances = [_]transcribe.Utterance{
        .{ .start_sec = 3599.7, .end_sec = 3661.4, .speaker = 2, .text = @constCast("Yes | no\nmaybe") },
    };
    const doc = try render(std.testing.allocator, .{
        .title = "20260826-090000",
        .resource = "recordings/long.wav",
        .timestamp = "2026-08-26T12:00:00Z",
        .model = "nova-3",
        .language = "en",
        .duration_sec = null,
    }, &utterances);
    defer std.testing.allocator.free(doc);

    try std.testing.expectEqualStrings(
        \\---
        \\type: Recording Transcript
        \\title: 20260826-090000
        \\description: Transcript of recordings/long.wav generated by Deepgram nova-3.
        \\resource: recordings/long.wav
        \\tags: [recording, transcript]
        \\timestamp: 2026-08-26T12:00:00Z
        \\model: nova-3
        \\language: en
        \\---
        \\
        \\Yes | no
        \\maybe
        \\
    , doc);
}

test "quotes yaml scalars that plain style would misread" {
    const doc = try render(std.testing.allocator, .{
        .title = "note: draft",
        .resource = "recordings/r.wav",
        .timestamp = "2026-08-26T12:00:00Z",
        .model = "nova-3",
        .language = "pt-BR",
        .duration_sec = null,
    }, &.{});
    defer std.testing.allocator.free(doc);

    try std.testing.expect(std.mem.indexOf(u8, doc, "title: \"note: draft\"\n") != null);
    try std.testing.expect(std.mem.indexOf(u8, doc, "resource: recordings/r.wav\n") != null);
}
